# Page settings
baseurl = "https://www.redontennis.fr"
title = "Redon Tennis - la nouvelle association de Tennis de Redon"
languageCode = "fr-fr"
theme = "hugo-elate-theme"
publishDir = "docs"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Johann Bourcier"
  description = "Redon Tennis - la nouvelle association de Tennis de Redon"
  email = "redon.tennis@gmail.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "Redon Tennis"
    home = "Redon Tennis"
    work = "Infrastructures"
    testimonials = "Témoignages"
    services = "Enseignement et tarifs"
    about = "Les personnes"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Redon Tennis"
    subtitle = 'Venez partagez notre passion et la vie de notre club de Tennis'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Compétition Loisir et Fitness"
    description = "Nous offrons une large gamme de cours pour les personnes désirant pratiquer le tennis en loisir, fitness ou compétition. Nous offrons un enseignement qualitatif pour les jeunes et les adultes. "
    icon = "icon-trophy"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Permanences et inscriptions"
    description = "Permanences pour les inscriptions au club le 06-09-2019 de 17h à 20h, le 07-09-2019 de 10h à 12h30 et au forum des associations le 08-09-2019 de 10h à 17h. Le club offrira dès cette année des permanences avec la présence des enseignants ou des membres du bureau. Les horaires de permanences seront misent à jour."
    icon = "icon-glass"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Affection de Longue Durée"
    description = "Nous lancons une nouvelle initiative sport-santé avec une nouvelle offre dédiée pour les personnes atteinte d'une affection de longue durée. Ces personnes seront prises en charge par un enseignant spécifiquement formé"
    icon = "icon-medkit"
    img = "img_10.jpg"


 # [params.intro.video]
 #   enable = true
 #   title = "Watch the video"
 #   icon = "icon-play2"
 #   url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Infrastructures"
    description = "Nos infrastructures comprennent 2 courts couverts ainsi que 2 courts extérieurs ainsi que 2 club houses des vestiaires et douches sur le même site"
    footertext = ''

    [[params.work.row]]
      img = "court3.jpg"
      alt = "Court numéro 1 extérieur"
      title = "Court numéro 1 extérieur"
      subtitle = "Béton poreux"

    [[params.work.row]]
      img = "court4.jpg"
      alt = "Court numéro 2 extérieur"
      title = "Court numéro 2 extérieur"
      subtitle = "Béton poreux"

    [[params.work.row]]
      img = "court1.jpg"
      alt = "Court numéro 1 couvert"
      title = "Court numéro 1 couvert"
      subtitle = "Béton"

    [[params.work.row]]
      img = "court2.jpg"
      alt = "Court numéro 2 couvert"
      title = "Court numéro 2 couvert"
      subtitle = "Plastique"

    [[params.work.row]]
      img = "clubHouse1.jpg"
      alt = "Club house"
      title = "Club house"
      subtitle = ""

    [[params.work.row]]
      img = "clubHouse2.jpg"
      alt = "Bureau du club"
      title = "Bureau du club"
      subtitle = ""



  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Témoignages"
    description = "Les paroles de nos membres"

    [[params.testimonials.item]]
      quote = "&ldquo;Je vous souhaite la bienvenue à Redon Tennis et espère vous croiser prochainement sur nos courts.&rdquo;"
      person = 'Johann Bourcier <span class="subtext">Président</span>'
      img = "johann.jpg"
      alt = "Johann Bourcier"

    [[params.testimonials.item]]
      quote = "&ldquo;A venir&rdquo;"
      person = 'Maurepas Auguste<span class="subtext">Vice-président</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;A venir&rdquo;"
      person = 'Solenn Le Gal, <span class="subtext">Enseignante principale</span>'
      img = "Solenn.jpg"
      alt = "Solenn"




  # Services section
  [params.services]
    enable = true
    title = "Enseignements et tarifs"
    description = 'Redon Tennis propose une offre variée pour la pratique du Tennis : adhésion pour accéder aux infrastructures ; entrainement intensif en vue de la compétition ainsi que le tennis loisir santé et bien être. Toutes nos formules inclus la licence FFT! Toutes les formules sont payable en 3 fois. Nous acceptons les chèques sports de la ville de Redon. <b>Les tarifs annuels pour 2019-2020 sont disponible <a href="documents/flyer2019_2020.pdf" target="_blank">ici</a></b>'

    [[params.services.item]]
      title = "Adhésion"
      description = 'Cette formule vous permet un accès aux infrastructures de Tennis : les 2 courts couverts ainsi que les 2 courts extérieurs. Vous aurez accès à un système de réservation des courts en ligne. <b>Les tarifs annuels pour 2019-2020 sont disponible <a href="documents/flyer2019_2020.pdf" target="_blank">ici</a></b>'
      icon = "icon-ticket"

    [[params.services.item]]
      title = "Loisir ou Tennis Fitness"
      description = 'Cette formule vous donne accès aux infrastructures de Tennis et 1h30/semaine de pratique spécifique avec un enseignement pratiqué en groupe. <b>Les tarifs annuels pour 2019-2020 sont disponible <a href="documents/flyer2019_2020.pdf" target="_blank">ici</a></b>.'
      icon = "icon-glass"
    [[params.services.item]]
      title = "Compétition"
      description = 'Cette formule vous permet un accès aux infrastructures de Tennis et entre 1 et 3 heure de pratique spécifique par semaine pratiqué en groupe avec un de nos 2 enseignants. <b>Les tarifs annuels pour 2019-2020 sont disponible <a href="documents/flyer2019_2020.pdf" target="_blank">ici</a></b>.'
      icon = "icon-trophy"

      [[params.services.item]]
      title = "Affection de Longue Durée"
      description = 'Cette formule vous permet un accès aux infrastructures de Tennis et 1 heure de pratique spécifique par semaine pratiqué en groupe avec notre enseignant spécialisé. <b>Les tarifs annuels pour 2019-2020 sont disponible <a href="documents/flyer2019_2020.pdf" target="_blank">ici</a></b>'
      icon = "icon-medkit"

  # About section
  [params.about]
    enable = true
    title = "Personnes impliquées"
    description = "Les personnes impliquées dans l'association Redon Tennis."

    [[params.about.item]]
      name = "Johann Bourcier"
      position = "Président"
      description = "Johann est joueur de Tennis classé en 3ème série et à participé activement à la création de Redon Tennis"
      img = "johann.jpg"
      alt = "Johann Bourcier"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Fredy Auguste"
      position = "Vice-Président"
      description = "Fredy est joueur de Tennis et à participé activement à la création de Redon Tennis"
      img = "person1.jpg"
      alt = "Fredy Auguste"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Guillaume Le Bastard"
      position = "Trésorier"
      description = "Guillaume est joueur de Tennis et à participé activement à la création de Redon Tennis"
      img = "person2.jpg"
      alt = "Guillaume Le Bastard"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Elodie Le Brun"
      position = "Trésorière adjointe"
      description = "Elodie est maman d'un joueur de Tennis et à participé activement à la création de Redon Tennis"
      img = "person3.jpg"
      alt = "Elodie Le Brun"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Philippe Rault"
      position = "Secrétaire Général"
      description = "Philippe est joueur de Tennis et à participé activement à la création de Redon Tennis"
      img = "person4.jpg"
      alt = "Philippe Rault"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Raphaël Goudin"
      position = "Secrétaire adjoint"
      description = "Raphaël est joueur de Tennis et a participer activement à la création de Redon Tennis"
      img = "person1.jpg"
      alt = "Raphaël Goudin"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

[[params.about.item]]
      name = "Solenn"
      position = "Enseignante principale"
      description = "Grand espoir du tennis Breton ses ambitions sportives furent stoppées par une grave blessure qui lui fait prendre la décision, dans un premier temps, de privilégier la fin de ses études du cycle secondaire. <br> Après l’obtention de son baccalauréat « le démon du Tennis » l’a reprise et elle a mis tout en œuvre pour obtenir son diplôme DEJEPS mention Tennis en 2017. Depuis elle a travaillé comme professeur à l’Académie de Tennis Autexier."
      img = "Solenn.jpg"
      alt = "Solenn"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Federico"
      position = "Enseignant adjoint"
      description = "D’origine Italo / Argentine, Federico fût l’un des meilleurs jeunes joueurs de Tennis en Argentine (N° 30 Argentin des moins de 16 ans) et il intégrera, également par la suite, le Ranking (classement) Professionnel Argentin à la 46ème place. Il fût le sparring partner de Renzo Olivo (83ème joueur mondial en 2016 / 2017). <br>Parallèlement il enseigne le Tennis depuis l’âge de 16 ans. <br> Voulant s’installer en France et y travailler il a décidé de consacrer la saison 2019/2020 à l’obtention du diplôme DEJEPS mention Tennis afin de valider ses compétences acquises en Argentine."
      img = "federico.jpg"
      alt = "Federico"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Philippe Le Mouel"
      position = "Enseignant spécialisé ALD"
      description = "Philippe le Mouel est notre enseignant de tennis sport santé diplômé. C'est lui qui encadrera les personnes atteintes d'affection de longue durée"
      img = "person2.jpg"
      alt = "Philippe Le Mouel"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Chiffres"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Joueurs heureux"
      icon = "icon-male"
      from = 0
      to = 150
      interval = 25
      speed = 2000

    [[params.counters.item]]
      description = "Enseignants passionnés"
      icon = "icon-male"
      from = 0
      to = 3
      interval = 1
      speed = 50

    [[params.counters.item]]
      description = "Balle de tennis fatiguées"
      icon = "icon-dribbble"
      from = 0
      to = 300
      interval = 25
      speed = 2000

    [[params.counters.item]]
      description = "Membre du bureau engagés"
      icon = "icon-people"
      from = 0
      to = 6
      interval = 1
      speed = 300

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Nous contacter"
    description = "Nos infrastrucutres sont situées au 13 rue Joseph Ricordel, 35600 Redon"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "13 rue Joseph Ricordel, <br> 35600 Redon"],
        ["icon-phone", "02-99-72-19-46"],
        ["icon-envelope", "redon.tennis@gmail.com"],
        ["icon-globe", '<a href="http://www.redontennis.fr/" target="_blank">redontennis.fr</a>']
      ]

    name = "Nom"
    email = "Email"
    phone = "Téléphone"
    message = "Message"
    button = "Envoyé un message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
